export interface AdjuntosCotizacionesIdSolicitud {
  idCotizacion:        string,
  TipoAdjunto:         string,
  s_FolioAdjunto:      string,
  s_FacturaAdjuntoPDF: string,
  s_FacturaAdjuntoXML: string
}

export interface CotizacionProductos {
  id:                            string,
  IdCotizacion:                  string,
  idProducto:                    string,
  s_FolioOrdenCompra:            string,
  s_NumeroContrato:              string,
  idProveedor:                   number,
  n_Cantidad:                    number,
  d_PrecioUnitario:              string,
  d_Descuento:                   string,
  d_IVA:                         string,
  d_Retencion:                   string,
  d_PrecioTotal:                 string,
  d_Total:                       string,
  s_Observaciones:               string,
  b_Ganadora:                    string,
  b_Solicitante:                 string,
  d_FechaInsercionSistema:       string,
  s_ObservacionesSolicitante:    string,
  S_PRODUCTO:                    string,
  S_PROVEEDOR:                   string,
  S_TipoProducto:                string,
  s_RutaArchivoContrato:         string,
  s_RutaInvocacionContrato:      string,
  idCondPago:                    string,
  idAdjuntosFacturacion:         string,
  s_RutaInvocacionPDF:           string,
  s_RutaInvocacionXML:           string,
  s_RutaInvocacionTransferencia: string,
  b_FacturaValida:               string,
  s_ObservacionesFactura:        string
}


	export interface CondicionesPago {
	idSolicitud: string,
	idCotizacion: string,
	s_RutaInvocacionPDF: string,
	s_RutaInvocacionXML: string,
	s_RutaInvocacionTransferencia: string,
	s_NombreComercial: string,
	id: string,
	s_FolioOrdenCompra: string,
	n_NumeroPago: string,
	d_FechaProgramada: string,
	s_Concepto: string,
	d_Monto: string,
	d_DescuentoTotal: string,
	s_Penalizacion: string,
	d_PorcentajePenalizacion: string,
	s_Estatus: string,
	n_Paso: string,
	s_Observaciones: string,
	idGrupoImpresionCondPago: string,
	n_ImpresionDispersion: string,
	b_FacturaValida: string,
	s_ObservacionesFactura: string,
	s_ClaveEmpleado: string,
	d_FechaInsercionSistema: string,
	s_RespuestaRegistraAnticipoWS: string,
	s_XmlPeticionRegistraAnticipoWS: string,
	d_FechaInvocacionRegistraAnticipoWS: string,
	s_RespuestaAplicaAnticipoWS: string,
	s_XmlPeticionAplicaAnticipoWS: string,
	d_FechaInvocacionAplicaAnticipoWS: string,
	s_XmlPagoBancarioProv: string,
	s_RespuestaPagoBancarioProv: string,
	d_FechaInvocacionPagoBancarioProv: string,
	s_XmlRegistraPagoProv: string,
	s_RespuestaRegistraPagoProv: string,
	d_FechaInvocacionRegistraPagoProv: string,
	b_FacturaGeneral: string,
	idAdjuntosFacturacion: string,
	s_RespuestaWS: string,
  s_Descripcion: string
}
